name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer local directory
      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      # Use Docker to build the app with Buildozer
      - name: Build with Buildozer (via Docker)
        run: |
          docker run --rm \
          -v $(pwd):/home/user/hostcwd \
          -w /home/user/hostcwd \
          kivy/buildozer:4.0.0 \
          buildozer android debug

      # Upload the built APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-package
          path: bin/*.apk # Adjust this path based on your Buildozer configuration
