name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install dependencies and setup (as per previous configuration)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv git zip unzip openjdk-17-jdk wget curl
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv

      # Step 1: Cache Buildozer directories
      - name: Cache Buildozer directories
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      # Step 2: Build with Buildozer
      - name: Build with Buildozer
        run: buildozer android debug

      # Step 3: Upload artifacts (APK files)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*

      # Step 4: Clean up orphan processes and files
      - name: Clean up orphan processes
        run: |
          echo "Checking for orphan processes..."
          
          # Identify orphan processes (processes with no parent)
          orphan_processes=$(ps -eo pid,ppid,state,command | awk '$2 == 1 { print $1 }')

          if [ -n "$orphan_processes" ]; then
            echo "Found orphan processes, terminating them..."
            for pid in $orphan_processes; do
              kill -9 $pid || echo "Failed to terminate process $pid"
            done
          else
            echo "No orphan processes found."
          fi

          # Clean up temporary files (optional)
          echo "Cleaning up temporary files..."
          rm -rf /home/runner/work/_temp/*
          echo "Orphan processes cleanup complete!"
